name = "Ghostium"
license = "MIT"
licenselink = "http://sm.mit-license.org/"
description = "Port of oswaldoacauan's ghostium theme to Hugo"
homepage = "https://github.com/cxfksword/ghostium"
tags = ["blog", "ghostium"]
features = ["blog"]
min_version = 0.14

[author]
  name = "cxfksword"
  homepage = "http://cxfksword.coding.io"

# If porting an existing theme
[original]
  name = "oswaldoacauan"
  homepage = "https://github.com/oswaldoacauan/ghostium/"
  repo = "https://github.com/oswaldoacauan/ghostium/"
